
USE webapp;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    age INT,
    city VARCHAR(50)
);

INSERT INTO users (first_name, last_name, email, age, city) VALUES
('Anna', 'Davis', 'anna.davis0@example.com', 48, 'San Antonio'),
('Jane', 'Miller', 'jane.miller1@example.com', 22, 'Phoenix'),
('William', 'Lee', 'william.lee2@example.com', 47, 'New York'),
('Sam', 'Davis', 'sam.davis3@example.com', 43, 'Phoenix'),
('William', 'Davis', 'william.davis4@example.com', 32, 'Austin'),
('Sarah', 'Johnson', 'sarah.johnson5@example.com', 41, 'Philadelphia'),
('Emily', 'Davis', 'emily.davis6@example.com', 28, 'Austin'),
('Anna', 'Doe', 'anna.doe7@example.com', 38, 'Chicago'),
('Anna', 'Brown', 'anna.brown8@example.com', 59, 'Phoenix'),
('Sarah', 'Garcia', 'sarah.garcia9@example.com', 55, 'Phoenix'),
('Jessica', 'Miller', 'jessica.miller10@example.com', 40, 'New York'),
('Anna', 'Smith', 'anna.smith11@example.com', 40, 'Austin'),
('Jessica', 'Taylor', 'jessica.taylor12@example.com', 27, 'New York'),
('Michael', 'Doe', 'michael.doe13@example.com', 37, 'Phoenix'),
('Anna', 'Johnson', 'anna.johnson14@example.com', 29, 'Dallas'),
('John', 'Taylor', 'john.taylor15@example.com', 27, 'Chicago'),
('Michael', 'Davis', 'michael.davis16@example.com', 31, 'San Antonio'),
('Sarah', 'Lee', 'sarah.lee17@example.com', 58, 'Chicago'),
('Sarah', 'Wilson', 'sarah.wilson18@example.com', 50, 'Dallas'),
('William', 'Wilson', 'william.wilson19@example.com', 35, 'Phoenix'),
('Jessica', 'Davis', 'jessica.davis20@example.com', 30, 'Chicago'),
('Jessica', 'Brown', 'jessica.brown21@example.com', 54, 'San Diego'),
('Anna', 'Miller', 'anna.miller22@example.com', 49, 'Los Angeles'),
('Michael', 'Wilson', 'michael.wilson23@example.com', 21, 'Philadelphia'),
('Jane', 'Johnson', 'jane.johnson24@example.com', 52, 'Dallas'),
('Sam', 'Davis', 'sam.davis25@example.com', 50, 'Houston'),
('Michael', 'Johnson', 'michael.johnson26@example.com', 57, 'New York'),
('Anna', 'Lee', 'anna.lee27@example.com', 29, 'Austin'),
('John', 'Wilson', 'john.wilson28@example.com', 24, 'Chicago'),
('Sarah', 'Lee', 'sarah.lee29@example.com', 45, 'Phoenix'),
('Anna', 'Doe', 'anna.doe30@example.com', 33, 'New York'),
('Sam', 'Doe', 'sam.doe31@example.com', 39, 'San Antonio'),
('John', 'Smith', 'john.smith32@example.com', 26, 'Austin'),
('Emily', 'Brown', 'emily.brown33@example.com', 55, 'Houston'),
('Michael', 'Smith', 'michael.smith34@example.com', 33, 'Phoenix'),
('John', 'Davis', 'john.davis35@example.com', 50, 'Los Angeles'),
('David', 'Brown', 'david.brown36@example.com', 40, 'Houston'),
('Jessica', 'Davis', 'jessica.davis37@example.com', 49, 'Los Angeles'),
('Sam', 'Taylor', 'sam.taylor38@example.com', 58, 'San Diego'),
('Michael', 'Garcia', 'michael.garcia39@example.com', 26, 'Austin'),
('David', 'Taylor', 'david.taylor40@example.com', 24, 'Dallas'),
('Emily', 'Smith', 'emily.smith41@example.com', 48, 'New York'),
('William', 'Brown', 'william.brown42@example.com', 31, 'New York'),
('Jessica', 'Taylor', 'jessica.taylor43@example.com', 41, 'Philadelphia'),
('John', 'Smith', 'john.smith44@example.com', 53, 'Los Angeles'),
('David', 'Davis', 'david.davis45@example.com', 60, 'San Diego'),
('David', 'Lee', 'david.lee46@example.com', 41, 'San Diego'),
('Jessica', 'Lee', 'jessica.lee47@example.com', 20, 'Philadelphia'),
('Michael', 'Brown', 'michael.brown48@example.com', 26, 'San Antonio'),
('David', 'Taylor', 'david.taylor49@example.com', 31, 'San Antonio'),
('Emily', 'Smith', 'emily.smith50@example.com', 48, 'San Diego'),
('William', 'Wilson', 'william.wilson51@example.com', 22, 'Dallas'),
('Jane', 'Brown', 'jane.brown52@example.com', 48, 'New York'),
('William', 'Davis', 'william.davis53@example.com', 34, 'Los Angeles'),
('Michael', 'Smith', 'michael.smith54@example.com', 37, 'San Diego'),
('Michael', 'Doe', 'michael.doe55@example.com', 54, 'Chicago'),
('John', 'Doe', 'john.doe56@example.com', 26, 'Chicago'),
('Jane', 'Brown', 'jane.brown57@example.com', 50, 'Chicago'),
('Jane', 'Brown', 'jane.brown58@example.com', 45, 'Los Angeles'),
('Sam', 'Johnson', 'sam.johnson59@example.com', 40, 'Los Angeles'),
('Sam', 'Miller', 'sam.miller60@example.com', 47, 'New York'),
('Michael', 'Doe', 'michael.doe61@example.com', 32, 'Austin'),
('Jane', 'Miller', 'jane.miller62@example.com', 27, 'Austin'),
('Sam', 'Davis', 'sam.davis63@example.com', 45, 'Austin'),
('John', 'Johnson', 'john.johnson64@example.com', 25, 'Austin'),
('John', 'Taylor', 'john.taylor65@example.com', 47, 'Houston'),
('Anna', 'Davis', 'anna.davis66@example.com', 40, 'Austin'),
('William', 'Johnson', 'william.johnson67@example.com', 27, 'Chicago'),
('John', 'Taylor', 'john.taylor68@example.com', 26, 'Los Angeles'),
('Jane', 'Johnson', 'jane.johnson69@example.com', 48, 'Philadelphia'),
('Anna', 'Smith', 'anna.smith70@example.com', 24, 'Houston'),
('Jessica', 'Miller', 'jessica.miller71@example.com', 20, 'Phoenix'),
('Emily', 'Smith', 'emily.smith72@example.com', 28, 'San Diego'),
('Sam', 'Doe', 'sam.doe73@example.com', 56, 'San Diego'),
('Sam', 'Wilson', 'sam.wilson74@example.com', 29, 'Austin'),
('Anna', 'Taylor', 'anna.taylor75@example.com', 60, 'Los Angeles'),
('John', 'Taylor', 'john.taylor76@example.com', 43, 'San Antonio'),
('Jane', 'Doe', 'jane.doe77@example.com', 26, 'Dallas'),
('Michael', 'Davis', 'michael.davis78@example.com', 52, 'Chicago'),
('Anna', 'Brown', 'anna.brown79@example.com', 33, 'San Diego'),
('Emily', 'Lee', 'emily.lee80@example.com', 53, 'Phoenix'),
('David', 'Brown', 'david.brown81@example.com', 26, 'San Antonio'),
('William', 'Johnson', 'william.johnson82@example.com', 50, 'San Antonio'),
('Sam', 'Johnson', 'sam.johnson83@example.com', 36, 'San Antonio'),
('Sam', 'Johnson', 'sam.johnson84@example.com', 30, 'Los Angeles'),
('John', 'Smith', 'john.smith85@example.com', 29, 'Chicago'),
('Jessica', 'Miller', 'jessica.miller86@example.com', 54, 'San Diego'),
('John', 'Smith', 'john.smith87@example.com', 32, 'San Diego'),
('Michael', 'Brown', 'michael.brown88@example.com', 36, 'San Antonio'),
('Anna', 'Garcia', 'anna.garcia89@example.com', 23, 'San Diego'),
('Jane', 'Taylor', 'jane.taylor90@example.com', 22, 'Chicago'),
('Sam', 'Miller', 'sam.miller91@example.com', 50, 'Philadelphia'),
('William', 'Smith', 'william.smith92@example.com', 44, 'Phoenix'),
('Anna', 'Miller', 'anna.miller93@example.com', 43, 'Phoenix'),
('Jane', 'Brown', 'jane.brown94@example.com', 33, 'Phoenix'),
('Michael', 'Davis', 'michael.davis95@example.com', 26, 'San Antonio'),
('Sam', 'Davis', 'sam.davis96@example.com', 36, 'San Antonio'),
('John', 'Miller', 'john.miller97@example.com', 53, 'Houston'),
('Michael', 'Taylor', 'michael.taylor98@example.com', 39, 'Phoenix'),
('John', 'Brown', 'john.brown99@example.com', 27, 'Chicago');